import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: "Welcome to BiteBridge",
    subWelcome: "Share delicious home-cooked curries with neighbors, hostelers, and PG roommates at affordable prices.",
    loginWithGoogle: "Login with Google",
    dashboard: "Dashboard",
    nearbyFeed: "Nearby Feed",
    createPost: "Share Food",
    rooms: "Rooms",
    profile: "Profile",
    notifications: "Notifications",
    logout: "Logout",
    toggleDark: "Dark Mode",
    toggleLight: "Light Mode",
    exploreCurries: "Explore Curries Nearby",
    freshHomemade: "Fresh, homemade meals shared with trust.",
    availableNow: "Available Now",
    createRoom: "Create a Room",
    joinRoom: "Join a Room",
    postedByRoom: "Posted by Room",
    requestFood: "Request Food",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    quantity: "Quantity",
    price: "Price",
    free: "Free",
    location: "Location",
    availability: "Available Till",
    roomIdPlaceholder: "Enter Room Code to Join",
    submit: "Submit",
    cancel: "Cancel",
    admin: "Admin",
    roomMembers: "Room Members",
    joinRequests: "Join Requests",
    noRoomsMessage: "You have not joined any PG/Hostel room groups yet.",
    createNewRoomTitle: "Create your hostel/PG sharing group room",
    roomName: "Room Name",
    roomDescription: "Room Description",
    roomCode: "Room Code",
    nearbyPosts: "Nearby Food sharing feed"
  },
  te: {
    welcome: "బైట్‌బ్రిడ్జ్ కి స్వాగతం",
    subWelcome: "పక్కన ఉన్న స్నేహితులు మరియు హాస్టల్ మిత్రులతో తక్కువ ధరలలో రుచికరమైన ఇంటి వంటలను పంచుకోండి.",
    loginWithGoogle: "గూగుల్ తో లాగిన్ అవ్వండి",
    dashboard: "డాష్‌బోర్డ్",
    nearbyFeed: "సమీప ఫీడ్",
    createPost: "ఆహారాన్ని పంచుకోండి",
    rooms: "రూములు",
    profile: "ప్రొఫైల్",
    notifications: "సమాచారాలు",
    logout: "లాగ్అవుట్",
    toggleDark: "చీకటి మోడ్",
    toggleLight: "వెలుతురు మోడ్",
    exploreCurries: "సమీపంలోని కూరలను అన్వేషించండి",
    freshHomemade: "నమ్మకంతో పంచుకునే తాజా ఇంటి భోజనం.",
    availableNow: "ఇప్పుడు అందుబాటులో ఉంది",
    createRoom: "రూమ్ సృష్టించండి",
    joinRoom: "రూమ్ లో చేరండి",
    postedByRoom: "రూమ్ ద్వారా పోస్ట్ చేయబడింది",
    requestFood: "ఆహారాన్ని అభ్యర్థించండి",
    pending: "పెండింగ్",
    accepted: "ఆమోదించబడింది",
    rejected: "తిరస్కరించబడింది",
    quantity: "పరిమాణం",
    price: "ధర",
    free: "ఉచితం",
    location: "ప్రదేశం",
    availability: "అందుబాటు సమయం",
    roomIdPlaceholder: "చేరడానికి రూమ్ కోడ్ నమోదు చేయండి",
    submit: "సమర్పించు",
    cancel: "రద్దు చేయి",
    admin: "అడ్మిన్",
    roomMembers: "సభ్యులు",
    joinRequests: "చేరడానికి అభ్యర్థనలు",
    noRoomsMessage: "మీరు ఇంకా ఏ హాస్టల్/పిజి రూమ్ గ్రూపుల్లో చేరలేదు.",
    createNewRoomTitle: "మీ హాస్టల్/పిజి రూమ్ ను సృష్టించండి",
    roomName: "రూమ్ పేరు",
    roomDescription: "రూమ్ వివరణ",
    roomCode: "రూమ్ కోడ్",
    nearbyPosts: "సమీప ఆహార ఫీడ్"
  },
  hi: {
    welcome: "बाइटब्रिज में आपका स्वागत है",
    subWelcome: "अपने पड़ोसियों, हॉस्टल के साथियों और पीजी रूममेट्स के साथ किफायती कीमतों पर स्वादिष्ट घर का बना खाना साझा करें।",
    loginWithGoogle: "गूगल के साथ लॉगिन करें",
    dashboard: "डैशबोर्ड",
    nearbyFeed: "आसपास की फीड",
    createPost: "भोजन साझा करें",
    rooms: "रूम्स",
    profile: "प्रोफाइल",
    notifications: "सूचनाएं",
    logout: "लॉगआउट",
    toggleDark: "डार्क मोड",
    toggleLight: "लाइट मोड",
    exploreCurries: "आसपास के व्यंजनों को खोजें",
    freshHomemade: "विश्वास के साथ साझा किया गया ताज़ा, घर का बना भोजन।",
    availableNow: "अभी उपलब्ध",
    createRoom: "रूम बनाएं",
    joinRoom: "रूम में शामिल हों",
    postedByRoom: "रूम द्वारा पोस्ट किया गया",
    requestFood: "भोजन का अनुरोध करें",
    pending: "लंबित",
    accepted: "स्वीकृत",
    rejected: "अस्वीकृत",
    quantity: "मात्रा",
    price: "कीमत",
    free: "मुफ़्त",
    location: "स्थान",
    availability: "उपलब्धता समय",
    roomIdPlaceholder: "शामिल होने के लिए रूम कोड डालें",
    submit: "जमा करें",
    cancel: "रद्द करें",
    admin: "एडमिन",
    roomMembers: "रूम सदस्य",
    joinRequests: "शामिल होने के अनुरोध",
    noRoomsMessage: "आप अभी तक किसी पीजी/हॉस्टल रूम ग्रुप में शामिल नहीं हुए हैं।",
    createNewRoomTitle: "अपना हॉस्टल/पीजी शेयरिंग रूम बनाएं",
    roomName: "रूम का नाम",
    roomDescription: "रूम का विवरण",
    roomCode: "रूम कोड",
    nearbyPosts: "आसपास के भोजन साझाकरण"
  },
  ta: {
    welcome: "பைட் பிரிட்ஜ் உங்களை வரவேற்கிறது",
    subWelcome: "உங்களது அண்டை வீட்டார் மற்றும் ஹாஸ்டல் தோழர்களுடன் சுவையான வீட்டு உணவுகளை மலிவு விலையில் பகிர்ந்து கொள்ளுங்கள்.",
    loginWithGoogle: "கூகிள் மூலம் உள்நுழையவும்",
    dashboard: "டாஷ்போர்டு",
    nearbyFeed: "அருகிலுள்ள ஃபீட்",
    createPost: "உணவை பகிர்ந்து கொள்ளுங்கள்",
    rooms: "அறைகள்",
    profile: "விவரக்குறிப்பு",
    notifications: "அறிவிப்புகள்",
    logout: "வெளியேறு",
    toggleDark: "இருண்ட பயன்முறை",
    toggleLight: "ஒளி பயன்முறை",
    exploreCurries: "அருகிலுள்ள உணவுகளை ஆராயுங்கள்",
    freshHomemade: "நம்பிக்கையுடன் பகிரப்படும் புதிய வீட்டு உணவு.",
    availableNow: "இப்போது கிடைக்கும்",
    createRoom: "அறையை உருவாக்குங்கள்",
    joinRoom: "அறையில் இணையுங்கள்",
    postedByRoom: "அறை மூலம் பகிரப்பட்டது",
    requestFood: "உணவு கேட்கவும்",
    pending: "நிலுவையில் உள்ளது",
    accepted: "ஏற்கப்பட்டது",
    rejected: "நிராகரிக்கப்பட்டது",
    quantity: "அளவு",
    price: "விலை",
    free: "இலவசம்",
    location: "இடம்",
    availability: "இருக்கும் நேரம்",
    roomIdPlaceholder: "இணைய அறை குறியீட்டை உள்ளிடவும்",
    submit: "சமர்ப்பி",
    cancel: "ரத்து செய்",
    admin: "நிர்வாகி",
    roomMembers: "அறை உறுப்பினர்கள்",
    joinRequests: "இணைவதற்கான கோரிக்கைகள்",
    noRoomsMessage: "நீங்கள் இன்னும் எந்த ஹாஸ்டல்/பிஜி அறை குழுவிலும் இணையவில்லை.",
    createNewRoomTitle: "உங்கள் ஹாஸ்டல்/பிஜி பகிர்வு அறையை உருவாக்குங்கள்",
    roomName: "அறையின் பெயர்",
    roomDescription: "அறையின் விளக்கம்",
    roomCode: "அறையின் குறியீடு",
    nearbyPosts: "அருகிலுள்ள உணவு பகிர்வு ஃபீட்"
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(() => localStorage.getItem('locale') || 'en');

  useEffect(() => {
    localStorage.setItem('locale', locale);
  }, [locale]);

  const t = (key) => {
    return translations[locale][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
